### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Poppe66** [SwedishForcesPack/SFP-JSRS-Sounds#3]
https://github.com/SwedishForcesPack/SFP-JSRS-Sounds/blob/d93991a8a422fd340f1b179fc6519342ea105331/source/sfp/jsrs/weapons/ak5/config.cpp#L21

JSRS does not apply the sound correctly. Shot closure and tail is not existing(soundset). Might be a change of class names from JSRS.

**Comment by Dahlgren** [comment]
Might be the case, JSRS just released a new version

**Comment by Poppe66** [comment]
False alarm. Techincal issues on client end.
